'use strict';
/* ---------- Kamus bahasa ID / EN ---------- */
const LANGKEY = 'reonzy-mp-maker-lang';
const FONTKEY = 'reonzy-mp-maker-font';
const I18N = {
  id: {
    tag: 'Pilih versi, pilih mod, unduh modpack.',
    desc: 'Susun modpack Minecraft: pilih versi, loader, mod, texture pack, dan shader. Versi yang cocok ditandai otomatis.',
    cfgAria: 'Pengaturan modpack', cfgTitle: 'Pengaturan pack',
    packName: 'Nama modpack', packVer: 'Versi', mcVer: 'Versi Minecraft',
    snap: 'Tampilkan snapshot dan versi pra-rilis', loader: 'Mod loader', loaderVer: 'Versi loader',
    lvManualPh: 'Ketik versi loader', pickMode: 'Cara memilih versi mod',
    prefAuto: 'Utamakan release stabil, lalu beta, lalu alpha', prefNewest: 'Selalu yang paling baru',
    deps: 'Tambahkan mod pendukung yang wajib (misalnya Fabric API) secara otomatis',
    legendAria: 'Arti warna',
    lgOk: 'Hijau: versi cocok dengan Minecraft dan loader',
    lgWarn: 'Kuning: cocok, tetapi hanya beta atau alpha',
    lgBad: 'Merah: tidak ada versi yang cocok',
    browseAria: 'Cari konten', browseTitle: 'Cari konten', searchSr: 'Cari',
    searchPh: 'Cari nama, misalnya sodium atau complementary', more: 'Muat lebih banyak',
    packAria: 'Isi modpack', packTitle: 'Isi modpack',
    dlMrpack: 'Unduh modpack (.mrpack)', copy: 'Salin daftar', save: 'Simpan proyek',
    open: 'Buka proyek', clear: 'Kosongkan pack',
    mrpackHint: 'File .mrpack bisa diimpor ke Modrinth App, Prism Launcher, dan ATLauncher. Mod diunduh langsung dari Modrinth saat diimpor.',
    footer: 'Data mod, texture pack, dan shader berasal dari Modrinth. Reonzy MP Maker tidak berafiliasi dengan Mojang maupun Modrinth.',
    typeMod: 'Mod', typeModP: 'mod', typeRp: 'Texture pack', typeRpP: 'texture pack',
    typeShader: 'Shader', typeShaderP: 'shader',
    quiltHint: 'Quilt juga bisa menjalankan mod Fabric, jadi keduanya ikut dicari.',
    lvLoading: 'Memuat…', lvManualFail: 'Daftar versi loader tidak bisa dimuat. Ketik versinya sendiri.',
    lvNone: 'Belum ada {loader} untuk Minecraft {mc}. Pilih versi Minecraft atau loader lain.',
    lvAuto: 'Versi stabil terbaru dipilih otomatis.', betaTag: ' (beta)',
    tabHintShader: 'Shader butuh Iris atau OptiFine di launcher. Iris bisa ditambahkan dari tab Mod.',
    mcFirst: 'Pilih versi Minecraft dulu.',
    searchFail: 'Gagal menghubungi Modrinth. Periksa koneksi internet, lalu ',
    retry: 'coba lagi', searching: 'Mencari…', by: 'oleh ', downloads: 'unduhan',
    latest: 'terbaru ', viewModrinth: 'Lihat di Modrinth', add: 'Tambah', added: 'Sudah ada',
    noResults: 'Tidak ada {plural}{query} untuk {scope}.', withQuery: ' dengan kata "{q}"', withLoader: 'dengan {loader}',
    resCount: '{total} {plural} tersedia untuk {scope}.',
    findingVer: 'Mencari versi…', noVerFor: 'Tidak ada versi untuk {scope}',
    viewAll: 'Lihat semua versi', loadVerFail: 'Gagal memuat versi',
    changeVer: 'Ganti versi', match: 'Cocok', nomatch: 'Tidak cocok',
    mismatchNote: 'Versi ini dibuat untuk Minecraft atau loader lain dan mungkin tidak jalan.',
    betaNote: 'Belum ada release stabil untuk {scope}, jadi dipakai {type}.',
    needBy: 'Dibutuhkan oleh {who}', remove: 'Hapus {title}',
    tagOn: 'Saring tag {tag}', tagOff: 'Hapus saringan {tag}',
    activeTags: 'Tag aktif', clearTags: 'Hapus semua',
    menu: 'Menu', packBtn: 'Pack',
    reqTitle: 'Kebutuhan', reqMissing: 'kurang', reqOk: 'Terpenuhi', reqOpt: 'Opsional',
    reqAddAll: 'Tambahkan semua yang kurang', sumMissing: 'kebutuhan kurang',
    depAddFail: 'Gagal menambahkan mod kebutuhan.',
    emptyPack: 'Belum ada isi. Cari mod, texture pack, atau shader di sebelah, lalu klik Tambah.',
    sumItem: 'item', sumMatch: 'cocok', sumBad: 'bermasalah', sumLoading: 'dicari',
    dlgSub: 'Baris hijau cocok dengan {scope}. Versi yang disarankan ada di paling atas.',
    dlgLoading: 'Memuat semua versi…', dlgEmpty: 'Belum ada versi sama sekali.',
    suggested: 'Disarankan', showAll: 'Tampilkan semua versi (termasuk yang tidak cocok)',
    close: 'Tutup', copied: 'Daftar disalin.', clipDeny: 'Browser menolak akses clipboard.',
    opened: 'Proyek dibuka.', invalidProj: 'File proyek tidak valid.',
    confirmClear: 'Kosongkan semua isi pack?',
    mcListFail: 'Tidak bisa memuat daftar versi Minecraft dari Modrinth. Periksa koneksi internet, lalu muat ulang halaman.',
    needLoaderVer: 'Isi versi loader dulu sebelum mengunduh.',
    zipNotReady: 'Pustaka ZIP belum selesai dimuat. Coba lagi sebentar.',
    dlDone: 'Modpack diunduh ({n} file).', dlSkip: ' {n} item dilewati karena belum punya versi.',
    dlBad: ' {n} versi tidak cocok.',
    loadAllFail: 'Gagal memuat semua versi.',
    packMismatch: 'Versi ini tidak cocok dengan pengaturan pack. Pack bisa gagal jalan.',
    madeWith: 'Dibuat dengan Reonzy MP Maker', noVerYet: '(belum ada versi)',
    defaultName: 'Modpack Saya',
    cvAria: 'Konverter MRPack ke ZIP', cvTitle: 'Konverter .mrpack → .zip',
    cvDesc: 'Unggah file .mrpack, klik konversi, browser akan mengunduh semua mod dari Modrinth lalu file ZIP langsung terunduh ke komputermu. Tanpa server.',
    cvDropAria: 'Tarik file .mrpack ke sini atau klik untuk memilih',
    cvDrop: 'Tarik & letakkan file .mrpack di sini', cvBrowse: 'Pilih file',
    cvOptStruct: 'Pertahankan struktur folder (mods/, resourcepacks/, shaderpacks/)',
    cvOptDl: 'Unduh file mod dari Modrinth (wajib agar ZIP bisa dipakai)',
    cvOptNorm: 'Normalkan nama file (huruf kecil, spasi jadi strip)',
    cvConvert: 'Konversi & unduh ZIP',
    cvHint: 'Hasil ZIP berisi mod (.jar), resource pack, shader, dan file overrides — siap dipakai di launcher apa pun.',
    cvNoFile: 'Pilih file .mrpack dulu.', cvBadFile: 'File ini bukan .mrpack yang valid (modrinth.index.json tidak ditemukan).',
    cvNoIndex: 'modrinth.index.json tidak ditemukan di file ini.',
    cvIndexBad: 'modrinth.index.json rusak dan tidak bisa dibaca.',
    cvWorking: 'Memproses {name}…', cvFetching: 'Mengunduh {done}/{total} file…',
    cvDone: 'ZIP terunduh ({n} file).', cvFail: 'Konversi gagal: {msg}',
    cvNoDl: ' {n} file dilewati (unduhan dari Modrinth dimatikan).',
    cvNoFiles: 'Tidak ada file di dalam .mrpack ini.',
    selAll: 'Pilih semua', selItem: 'Pilih {title}',
    delSel: 'Hapus yang dipilih ({n})',
    confirmSelDel: 'Hapus {n} item yang dipilih dari pack?',
    settings: 'Pengaturan', settingsTitle: 'Pengaturan',
    setLangTitle: 'Bahasa', setFontTitle: 'Font pixel',
    setFontToggleAria: 'Nyalakan atau matikan font pixel',
    setFontHint: 'Matikan untuk memakai font standar yang lebih mudah dibaca di semua tulisan.'
  },
  en: {
    tag: 'Pick a version, pick mods, download the modpack.',
    desc: 'Build a Minecraft modpack: pick version, loader, mods, texture packs, and shaders. Matching versions are flagged automatically.',
    cfgAria: 'Modpack settings', cfgTitle: 'Pack settings',
    packName: 'Modpack name', packVer: 'Version', mcVer: 'Minecraft version',
    snap: 'Show snapshots and pre-release versions', loader: 'Mod loader', loaderVer: 'Loader version',
    lvManualPh: 'Type the loader version', pickMode: 'How to pick mod versions',
    prefAuto: 'Prefer stable releases, then beta, then alpha', prefNewest: 'Always the newest',
    deps: 'Automatically add required dependencies (e.g. Fabric API)',
    legendAria: 'Color key',
    lgOk: 'Green: version matches Minecraft and loader',
    lgWarn: 'Yellow: matches, but beta or alpha only',
    lgBad: 'Red: no matching version',
    browseAria: 'Browse content', browseTitle: 'Browse content', searchSr: 'Search',
    searchPh: 'Search names, e.g. sodium or complementary', more: 'Load more',
    packAria: 'Modpack contents', packTitle: 'Modpack contents',
    dlMrpack: 'Download modpack (.mrpack)', copy: 'Copy list', save: 'Save project',
    open: 'Open project', clear: 'Clear pack',
    mrpackHint: 'The .mrpack file can be imported into Modrinth App, Prism Launcher, and ATLauncher. Mods are downloaded directly from Modrinth on import.',
    footer: 'Mod, texture pack, and shader data comes from Modrinth. Reonzy MP Maker is not affiliated with Mojang or Modrinth.',
    typeMod: 'Mod', typeModP: 'mods', typeRp: 'Texture pack', typeRpP: 'texture packs',
    typeShader: 'Shader', typeShaderP: 'shaders',
    quiltHint: 'Quilt can also run Fabric mods, so both are searched.',
    lvLoading: 'Loading…', lvManualFail: 'The loader version list could not be loaded. Type the version yourself.',
    lvNone: 'No {loader} for Minecraft {mc} yet. Pick another Minecraft version or loader.',
    lvAuto: 'The latest stable version is selected automatically.', betaTag: ' (beta)',
    tabHintShader: 'Shaders need Iris or OptiFine in the launcher. Iris can be added from the Mod tab.',
    mcFirst: 'Pick a Minecraft version first.',
    searchFail: 'Could not reach Modrinth. Check your connection, then ',
    retry: 'try again', searching: 'Searching…', by: 'by ', downloads: 'downloads',
    latest: 'latest ', viewModrinth: 'View on Modrinth', add: 'Add', added: 'Added',
    noResults: 'No {plural}{query} for {scope}.', withQuery: ' matching "{q}"', withLoader: 'with {loader}',
    resCount: '{total} {plural} available for {scope}.',
    findingVer: 'Finding version…', noVerFor: 'No version for {scope}',
    viewAll: 'View all versions', loadVerFail: 'Failed to load versions',
    changeVer: 'Change version', match: 'Match', nomatch: 'No match',
    mismatchNote: 'This version was made for a different Minecraft version or loader and may not work.',
    betaNote: 'No stable release for {scope} yet, so {type} is used.',
    needBy: 'Required by {who}', remove: 'Remove {title}',
    tagOn: 'Filter by {tag}', tagOff: 'Remove {tag} filter',
    activeTags: 'Active tags', clearTags: 'Clear all',
    menu: 'Menu', packBtn: 'Pack',
    reqTitle: 'Requires', reqMissing: 'missing', reqOk: 'Satisfied', reqOpt: 'Optional',
    reqAddAll: 'Add all missing', sumMissing: 'missing requirements',
    depAddFail: 'Failed to add the required mod.',
    emptyPack: 'Nothing here yet. Search for mods, texture packs, or shaders and click Add.',
    sumItem: 'items', sumMatch: 'matching', sumBad: 'with issues', sumLoading: 'loading',
    dlgSub: 'Green rows match {scope}. The suggested version is at the top.',
    dlgLoading: 'Loading all versions…', dlgEmpty: 'No versions at all yet.',
    suggested: 'Suggested', showAll: 'Show all versions (including non-matching)',
    close: 'Close', copied: 'List copied.', clipDeny: 'Browser denied clipboard access.',
    opened: 'Project opened.', invalidProj: 'Invalid project file.',
    confirmClear: 'Clear everything in the pack?',
    mcListFail: 'Could not load the Minecraft version list from Modrinth. Check your connection, then reload the page.',
    needLoaderVer: 'Fill in the loader version before downloading.',
    zipNotReady: 'The ZIP library has not finished loading. Try again in a moment.',
    dlDone: 'Modpack downloaded ({n} files).', dlSkip: ' {n} items skipped (no version yet).',
    dlBad: ' {n} mismatched versions.',
    loadAllFail: 'Failed to load all versions.',
    packMismatch: 'This version does not match the pack settings. The pack may fail to run.',
    madeWith: 'Made with Reonzy MP Maker', noVerYet: '(no version yet)',
    defaultName: 'My Modpack',
    cvAria: 'MRPack to ZIP converter', cvTitle: '.mrpack → .zip converter',
    cvDesc: 'Upload an .mrpack file, click convert, and your browser downloads every mod from Modrinth then saves the ZIP straight to your computer. No server needed.',
    cvDropAria: 'Drop an .mrpack file here or click to choose one',
    cvDrop: 'Drag & drop your .mrpack file here', cvBrowse: 'Browse files',
    cvOptStruct: 'Keep folder structure (mods/, resourcepacks/, shaderpacks/)',
    cvOptDl: 'Download mod files from Modrinth (required for a usable ZIP)',
    cvOptNorm: 'Normalize filenames (lowercase, spaces to dashes)',
    cvConvert: 'Convert & download ZIP',
    cvHint: 'The resulting ZIP contains mods (.jar), resource packs, shaders, and override files — ready for any launcher.',
    cvNoFile: 'Pick an .mrpack file first.', cvBadFile: 'This is not a valid .mrpack (modrinth.index.json not found).',
    cvNoIndex: 'modrinth.index.json was not found in this file.',
    cvIndexBad: 'modrinth.index.json is broken and could not be read.',
    cvWorking: 'Processing {name}…', cvFetching: 'Downloading {done}/{total} files…',
    cvDone: 'ZIP downloaded ({n} files).', cvFail: 'Conversion failed: {msg}',
    cvNoDl: ' {n} files skipped (downloading from Modrinth is off).',
    cvNoFiles: 'There are no files inside this .mrpack.',
    selAll: 'Select all', selItem: 'Select {title}',
    delSel: 'Delete selected ({n})',
    confirmSelDel: 'Remove {n} selected items from the pack?',
    settings: 'Settings', settingsTitle: 'Settings',
    setLangTitle: 'Language', setFontTitle: 'Pixel font',
    setFontToggleAria: 'Turn the pixel font on or off',
    setFontHint: 'Turn off to use the standard font, easier to read everywhere.'
  }
};
function tr(key, vars) {
  const lang = (typeof S !== 'undefined' && S.lang) || 'en';
  let s = (I18N[lang] && I18N[lang][key]) ?? I18N.en[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = String(s).replaceAll('{' + k + '}', v);
  return s;
}
function typeLabel(ty) {
  return ty === 'mod' ? tr('typeMod') : ty === 'resourcepack' ? tr('typeRp') : tr('typeShader');
}
function typePlural(ty) {
  return ty === 'mod' ? tr('typeModP') : ty === 'resourcepack' ? tr('typeRpP') : tr('typeShaderP');
}
